module.exports = {
	BIBLE_BOOKS: {
		OLD_TESTAMENT: [
			'GEN',
			'EXO',
			'LEV',
			'NUM',
			'DEU',
			'JOS',
			'JDG',
			'RUT',
			'1SA',
			'2SA',
			'1KI',
			'2KI',
			'1CH',
			'2CH',
			'EZR',
			'NEH',
			'EST',
			'JOB',
			'PSA',
			'PRO',
			'ECC',
			'SNG',
			'ISA',
			'JER',
			'LAM',
			'EZK',
			'DAN',
			'HOS',
			'JOL',
			'AMO',
			'OBA',
			'JON',
			'MIC',
			'NAH',
			'HAB',
			'ZEP',
			'HAG',
			'ZEC',
			'MAL',
		],
		NEW_TESTAMENT: [
			'MAT',
			'MRK',
			'LUK',
			'JHN',
			'ACT',
			'ROM',
			'1CO',
			'2CO',
			'GAL',
			'EPH',
			'PHP',
			'COL',
			'1TH',
			'2TH',
			'1TI',
			'2TI',
			'TIT',
			'PHM',
			'HEB',
			'JAS',
			'1PE',
			'2PE',
			'1JN',
			'2JN',
			'3JN',
			'JUD',
			'REV',
		],
	},
	BOOK_MAPPING: {
		Genesis: 'GEN',
		Exodus: 'EXO',
		Leviticus: 'LEV',
		Numbers: 'NUM',
		Deuteronomy: 'DEU',
		Joshua: 'JOS',
		Judges: 'JDG',
		Ruth: 'RUT',
		'1 Samuel': '1SA',
		'2 Samuel': '2SA',
		'1 Kings': '1KI',
		'2 Kings': '2KI',
		'1 Chronicles': '1CH',
		'2 Chronicles': '2CH',
		Ezra: 'EZR',
		Nehemiah: 'NEH',
		Esther: 'EST',
		Job: 'JOB',
		Psalms: 'PSA',
		Proverbs: 'PRO',
		Ecclesiastes: 'ECC',
		'Song of Solomon': 'SNG',
		Isaiah: 'ISA',
		Jeremiah: 'JER',
		Lamentations: 'LAM',
		Ezekiel: 'EZK',
		Daniel: 'DAN',
		Hosea: 'HOS',
		Joel: 'JOL',
		Amos: 'AMO',
		Obadiah: 'OBA',
		Jonah: 'JON',
		Micah: 'MIC',
		Nahum: 'NAH',
		Habakkuk: 'HAB',
		Zephaniah: 'ZEP',
		Haggai: 'HAG',
		Zechariah: 'ZEC',
		Malachi: 'MAL',
		Matthew: 'MAT',
		Mark: 'MRK',
		Luke: 'LUK',
		John: 'JHN',
		Acts: 'ACT',
		Romans: 'ROM',
		'1 Corinthians': '1CO',
		'2 Corinthians': '2CO',
		Galatians: 'GAL',
		Ephesians: 'EPH',
		Philippians: 'PHP',
		Colossians: 'COL',
		'1 Thessalonians': '1TH',
		'2 Thessalonians': '2TH',
		'1 Timothy': '1TI',
		'2 Timothy': '2TI',
		Titus: 'TIT',
		Philemon: 'PHM',
		Hebrews: 'HEB',
		James: 'JAS',
		'1 Peter': '1PE',
		'2 Peter': '2PE',
		'1 John': '1JN',
		'2 John': '2JN',
		'3 John': '3JN',
		Jude: 'JUD',
		Revelation: 'REV',
	},
	HIGHLIGHT_COLORS: [
		{ id: 'yellow', name: 'Yellow', backgroundColor: 'rgba(255, 193, 7, 0.2)' },
		{ id: 'green', name: 'Green', backgroundColor: 'rgba(40, 167, 69, 0.2)' },
		{ id: 'blue', name: 'Blue', backgroundColor: 'rgba(0, 123, 255, 0.2)' },
		{ id: 'pink', name: 'Pink', backgroundColor: 'rgba(220, 53, 69, 0.2)' },
		{
			id: 'orange',
			name: 'Orange',
			backgroundColor: 'rgba(253, 126, 20, 0.2)',
		},
	],
}
