// Generated file: countryObject.js with flags
module.exports = {
	AD: {
		countryCode: 'AD',
		countryName: 'Andorra',
		currencyCode: 'EUR',
		population: '84000',
		capital: 'Andorra la Vella',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ad.svg',
	},
	AE: {
		countryCode: 'AE',
		countryName: 'United Arab Emirates',
		currencyCode: 'AED',
		population: '4975593',
		capital: 'Abu Dhabi',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ae.svg',
	},
	AF: {
		countryCode: 'AF',
		countryName: 'Afghanistan',
		currencyCode: 'AFN',
		population: '29121286',
		capital: 'Kabul',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/af.svg',
	},
	AG: {
		countryCode: 'AG',
		countryName: 'Antigua and Barbuda',
		currencyCode: 'XCD',
		population: '86754',
		capital: "St. John's",
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ag.svg',
	},
	AI: {
		countryCode: 'AI',
		countryName: 'Anguilla',
		currencyCode: 'XCD',
		population: '13254',
		capital: 'The Valley',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ai.svg',
	},
	AL: {
		countryCode: 'AL',
		countryName: 'Albania',
		currencyCode: 'ALL',
		population: '2986952',
		capital: 'Tirana',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/al.svg',
	},
	AM: {
		countryCode: 'AM',
		countryName: 'Armenia',
		currencyCode: 'AMD',
		population: '2968000',
		capital: 'Yerevan',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/am.svg',
	},
	AO: {
		countryCode: 'AO',
		countryName: 'Angola',
		currencyCode: 'AOA',
		population: '13068161',
		capital: 'Luanda',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ao.svg',
	},
	AQ: {
		countryCode: 'AQ',
		countryName: 'Antarctica',
		currencyCode: '',
		population: '0',
		capital: '',
		continentName: 'Antarctica',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/aq.svg',
	},
	AR: {
		countryCode: 'AR',
		countryName: 'Argentina',
		currencyCode: 'ARS',
		population: '41343201',
		capital: 'Buenos Aires',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ar.svg',
	},
	AS: {
		countryCode: 'AS',
		countryName: 'American Samoa',
		currencyCode: 'USD',
		population: '57881',
		capital: 'Pago Pago',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/as.svg',
	},
	AT: {
		countryCode: 'AT',
		countryName: 'Austria',
		currencyCode: 'EUR',
		population: '8205000',
		capital: 'Vienna',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/at.svg',
	},
	AU: {
		countryCode: 'AU',
		countryName: 'Australia',
		currencyCode: 'AUD',
		population: '21515754',
		capital: 'Canberra',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/au.svg',
	},
	AW: {
		countryCode: 'AW',
		countryName: 'Aruba',
		currencyCode: 'AWG',
		population: '71566',
		capital: 'Oranjestad',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/aw.svg',
	},
	AX: {
		countryCode: 'AX',
		countryName: 'Åland',
		currencyCode: 'EUR',
		population: '26711',
		capital: 'Mariehamn',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ax.svg',
	},
	AZ: {
		countryCode: 'AZ',
		countryName: 'Azerbaijan',
		currencyCode: 'AZN',
		population: '8303512',
		capital: 'Baku',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/az.svg',
	},
	BA: {
		countryCode: 'BA',
		countryName: 'Bosnia and Herzegovina',
		currencyCode: 'BAM',
		population: '4590000',
		capital: 'Sarajevo',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ba.svg',
	},
	BB: {
		countryCode: 'BB',
		countryName: 'Barbados',
		currencyCode: 'BBD',
		population: '285653',
		capital: 'Bridgetown',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bb.svg',
	},
	BD: {
		countryCode: 'BD',
		countryName: 'Bangladesh',
		currencyCode: 'BDT',
		population: '156118464',
		capital: 'Dhaka',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bd.svg',
	},
	BE: {
		countryCode: 'BE',
		countryName: 'Belgium',
		currencyCode: 'EUR',
		population: '10403000',
		capital: 'Brussels',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/be.svg',
	},
	BF: {
		countryCode: 'BF',
		countryName: 'Burkina Faso',
		currencyCode: 'XOF',
		population: '16241811',
		capital: 'Ouagadougou',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bf.svg',
	},
	BG: {
		countryCode: 'BG',
		countryName: 'Bulgaria',
		currencyCode: 'BGN',
		population: '7148785',
		capital: 'Sofia',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bg.svg',
	},
	BH: {
		countryCode: 'BH',
		countryName: 'Bahrain',
		currencyCode: 'BHD',
		population: '738004',
		capital: 'Manama',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bh.svg',
	},
	BI: {
		countryCode: 'BI',
		countryName: 'Burundi',
		currencyCode: 'BIF',
		population: '9863117',
		capital: 'Bujumbura',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bi.svg',
	},
	BJ: {
		countryCode: 'BJ',
		countryName: 'Benin',
		currencyCode: 'XOF',
		population: '9056010',
		capital: 'Porto-Novo',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bj.svg',
	},
	BL: {
		countryCode: 'BL',
		countryName: 'Saint Barthélemy',
		currencyCode: 'EUR',
		population: '8450',
		capital: 'Gustavia',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bl.svg',
	},
	BM: {
		countryCode: 'BM',
		countryName: 'Bermuda',
		currencyCode: 'BMD',
		population: '65365',
		capital: 'Hamilton',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bm.svg',
	},
	BN: {
		countryCode: 'BN',
		countryName: 'Brunei',
		currencyCode: 'BND',
		population: '395027',
		capital: 'Bandar Seri Begawan',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bn.svg',
	},
	BO: {
		countryCode: 'BO',
		countryName: 'Bolivia',
		currencyCode: 'BOB',
		population: '9947418',
		capital: 'Sucre',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bo.svg',
	},
	BQ: {
		countryCode: 'BQ',
		countryName: 'Bonaire',
		currencyCode: 'USD',
		population: '18012',
		capital: 'Kralendijk',
		continentName: 'North America',
	},
	BR: {
		countryCode: 'BR',
		countryName: 'Brazil',
		currencyCode: 'BRL',
		population: '201103330',
		capital: 'Brasília',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/br.svg',
	},
	BS: {
		countryCode: 'BS',
		countryName: 'Bahamas',
		currencyCode: 'BSD',
		population: '301790',
		capital: 'Nassau',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bs.svg',
	},
	BT: {
		countryCode: 'BT',
		countryName: 'Bhutan',
		currencyCode: 'BTN',
		population: '699847',
		capital: 'Thimphu',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bt.svg',
	},
	BV: {
		countryCode: 'BV',
		countryName: 'Bouvet Island',
		currencyCode: 'NOK',
		population: '0',
		capital: '',
		continentName: 'Antarctica',
	},
	BW: {
		countryCode: 'BW',
		countryName: 'Botswana',
		currencyCode: 'BWP',
		population: '2029307',
		capital: 'Gaborone',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bw.svg',
	},
	BY: {
		countryCode: 'BY',
		countryName: 'Belarus',
		currencyCode: 'BYN',
		population: '9685000',
		capital: 'Minsk',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/by.svg',
	},
	BZ: {
		countryCode: 'BZ',
		countryName: 'Belize',
		currencyCode: 'BZD',
		population: '314522',
		capital: 'Belmopan',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/bz.svg',
	},
	CA: {
		countryCode: 'CA',
		countryName: 'Canada',
		currencyCode: 'CAD',
		population: '33679000',
		capital: 'Ottawa',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ca.svg',
	},
	CC: {
		countryCode: 'CC',
		countryName: 'Cocos [Keeling] Islands',
		currencyCode: 'AUD',
		population: '628',
		capital: 'West Island',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cc.svg',
	},
	CD: {
		countryCode: 'CD',
		countryName: 'Democratic Republic of the Congo',
		currencyCode: 'CDF',
		population: '70916439',
		capital: 'Kinshasa',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cd.svg',
	},
	CF: {
		countryCode: 'CF',
		countryName: 'Central African Republic',
		currencyCode: 'XAF',
		population: '4844927',
		capital: 'Bangui',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cf.svg',
	},
	CG: {
		countryCode: 'CG',
		countryName: 'Republic of the Congo',
		currencyCode: 'XAF',
		population: '3039126',
		capital: 'Brazzaville',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cg.svg',
	},
	CH: {
		countryCode: 'CH',
		countryName: 'Switzerland',
		currencyCode: 'CHF',
		population: '7581000',
		capital: 'Bern',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ch.svg',
	},
	CI: {
		countryCode: 'CI',
		countryName: 'Ivory Coast',
		currencyCode: 'XOF',
		population: '21058798',
		capital: 'Yamoussoukro',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ci.svg',
	},
	CK: {
		countryCode: 'CK',
		countryName: 'Cook Islands',
		currencyCode: 'NZD',
		population: '21388',
		capital: 'Avarua',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ck.svg',
	},
	CL: {
		countryCode: 'CL',
		countryName: 'Chile',
		currencyCode: 'CLP',
		population: '16746491',
		capital: 'Santiago',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cl.svg',
	},
	CM: {
		countryCode: 'CM',
		countryName: 'Cameroon',
		currencyCode: 'XAF',
		population: '19294149',
		capital: 'Yaoundé',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cm.svg',
	},
	CN: {
		countryCode: 'CN',
		countryName: 'China',
		currencyCode: 'CNY',
		population: '1330044000',
		capital: 'Beijing',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cn.svg',
	},
	CO: {
		countryCode: 'CO',
		countryName: 'Colombia',
		currencyCode: 'COP',
		population: '47790000',
		capital: 'Bogotá',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/co.svg',
	},
	CR: {
		countryCode: 'CR',
		countryName: 'Costa Rica',
		currencyCode: 'CRC',
		population: '4516220',
		capital: 'San José',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cr.svg',
	},
	CU: {
		countryCode: 'CU',
		countryName: 'Cuba',
		currencyCode: 'CUP',
		population: '11423000',
		capital: 'Havana',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cu.svg',
	},
	CV: {
		countryCode: 'CV',
		countryName: 'Cape Verde',
		currencyCode: 'CVE',
		population: '508659',
		capital: 'Praia',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cv.svg',
	},
	CW: {
		countryCode: 'CW',
		countryName: 'Curacao',
		currencyCode: 'ANG',
		population: '141766',
		capital: 'Willemstad',
		continentName: 'North America',
	},
	CX: {
		countryCode: 'CX',
		countryName: 'Christmas Island',
		currencyCode: 'AUD',
		population: '1500',
		capital: 'Flying Fish Cove',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cx.svg',
	},
	CY: {
		countryCode: 'CY',
		countryName: 'Cyprus',
		currencyCode: 'EUR',
		population: '1102677',
		capital: 'Nicosia',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cy.svg',
	},
	CZ: {
		countryCode: 'CZ',
		countryName: 'Czechia',
		currencyCode: 'CZK',
		population: '10476000',
		capital: 'Prague',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/cz.svg',
	},
	DE: {
		countryCode: 'DE',
		countryName: 'Germany',
		currencyCode: 'EUR',
		population: '81802257',
		capital: 'Berlin',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/de.svg',
	},
	DJ: {
		countryCode: 'DJ',
		countryName: 'Djibouti',
		currencyCode: 'DJF',
		population: '740528',
		capital: 'Djibouti',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/dj.svg',
	},
	DK: {
		countryCode: 'DK',
		countryName: 'Denmark',
		currencyCode: 'DKK',
		population: '5484000',
		capital: 'Copenhagen',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/dk.svg',
	},
	DM: {
		countryCode: 'DM',
		countryName: 'Dominica',
		currencyCode: 'XCD',
		population: '72813',
		capital: 'Roseau',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/dm.svg',
	},
	DO: {
		countryCode: 'DO',
		countryName: 'Dominican Republic',
		currencyCode: 'DOP',
		population: '9823821',
		capital: 'Santo Domingo',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/do.svg',
	},
	DZ: {
		countryCode: 'DZ',
		countryName: 'Algeria',
		currencyCode: 'DZD',
		population: '34586184',
		capital: 'Algiers',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/dz.svg',
	},
	EC: {
		countryCode: 'EC',
		countryName: 'Ecuador',
		currencyCode: 'USD',
		population: '14790608',
		capital: 'Quito',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ec.svg',
	},
	EE: {
		countryCode: 'EE',
		countryName: 'Estonia',
		currencyCode: 'EUR',
		population: '1291170',
		capital: 'Tallinn',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ee.svg',
	},
	EG: {
		countryCode: 'EG',
		countryName: 'Egypt',
		currencyCode: 'EGP',
		population: '80471869',
		capital: 'Cairo',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/eg.svg',
	},
	EH: {
		countryCode: 'EH',
		countryName: 'Western Sahara',
		currencyCode: 'MAD',
		population: '273008',
		capital: 'Laâyoune / El Aaiún',
		continentName: 'Africa',
	},
	ER: {
		countryCode: 'ER',
		countryName: 'Eritrea',
		currencyCode: 'ERN',
		population: '5792984',
		capital: 'Asmara',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/er.svg',
	},
	ES: {
		countryCode: 'ES',
		countryName: 'Spain',
		currencyCode: 'EUR',
		population: '46505963',
		capital: 'Madrid',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/es.svg',
	},
	ET: {
		countryCode: 'ET',
		countryName: 'Ethiopia',
		currencyCode: 'ETB',
		population: '88013491',
		capital: 'Addis Ababa',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/et.svg',
	},
	FI: {
		countryCode: 'FI',
		countryName: 'Finland',
		currencyCode: 'EUR',
		population: '5244000',
		capital: 'Helsinki',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/fi.svg',
	},
	FJ: {
		countryCode: 'FJ',
		countryName: 'Fiji',
		currencyCode: 'FJD',
		population: '875983',
		capital: 'Suva',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/fj.svg',
	},
	FK: {
		countryCode: 'FK',
		countryName: 'Falkland Islands',
		currencyCode: 'FKP',
		population: '2638',
		capital: 'Stanley',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/fk.svg',
	},
	FM: {
		countryCode: 'FM',
		countryName: 'Micronesia',
		currencyCode: 'USD',
		population: '107708',
		capital: 'Palikir',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/fm.svg',
	},
	FO: {
		countryCode: 'FO',
		countryName: 'Faroe Islands',
		currencyCode: 'DKK',
		population: '48228',
		capital: 'Tórshavn',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/fo.svg',
	},
	FR: {
		countryCode: 'FR',
		countryName: 'France',
		currencyCode: 'EUR',
		population: '64768389',
		capital: 'Paris',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/fr.svg',
	},
	GA: {
		countryCode: 'GA',
		countryName: 'Gabon',
		currencyCode: 'XAF',
		population: '1545255',
		capital: 'Libreville',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ga.svg',
	},
	GB: {
		countryCode: 'GB',
		countryName: 'United Kingdom',
		currencyCode: 'GBP',
		population: '62348447',
		capital: 'London',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gb.svg',
	},
	GD: {
		countryCode: 'GD',
		countryName: 'Grenada',
		currencyCode: 'XCD',
		population: '107818',
		capital: "St. George's",
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gd.svg',
	},
	GE: {
		countryCode: 'GE',
		countryName: 'Georgia',
		currencyCode: 'GEL',
		population: '4630000',
		capital: 'Tbilisi',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ge.svg',
	},
	GF: {
		countryCode: 'GF',
		countryName: 'French Guiana',
		currencyCode: 'EUR',
		population: '195506',
		capital: 'Cayenne',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gf.svg',
	},
	GG: {
		countryCode: 'GG',
		countryName: 'Guernsey',
		currencyCode: 'GBP',
		population: '65228',
		capital: 'St Peter Port',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gg.svg',
	},
	GH: {
		countryCode: 'GH',
		countryName: 'Ghana',
		currencyCode: 'GHS',
		population: '24339838',
		capital: 'Accra',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gh.svg',
	},
	GI: {
		countryCode: 'GI',
		countryName: 'Gibraltar',
		currencyCode: 'GIP',
		population: '27884',
		capital: 'Gibraltar',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gi.svg',
	},
	GL: {
		countryCode: 'GL',
		countryName: 'Greenland',
		currencyCode: 'DKK',
		population: '56375',
		capital: 'Nuuk',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gl.svg',
	},
	GM: {
		countryCode: 'GM',
		countryName: 'Gambia',
		currencyCode: 'GMD',
		population: '1593256',
		capital: 'Bathurst',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gm.svg',
	},
	GN: {
		countryCode: 'GN',
		countryName: 'Guinea',
		currencyCode: 'GNF',
		population: '10324025',
		capital: 'Conakry',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gn.svg',
	},
	GP: {
		countryCode: 'GP',
		countryName: 'Guadeloupe',
		currencyCode: 'EUR',
		population: '443000',
		capital: 'Basse-Terre',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gp.svg',
	},
	GQ: {
		countryCode: 'GQ',
		countryName: 'Equatorial Guinea',
		currencyCode: 'XAF',
		population: '1014999',
		capital: 'Malabo',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gq.svg',
	},
	GR: {
		countryCode: 'GR',
		countryName: 'Greece',
		currencyCode: 'EUR',
		population: '11000000',
		capital: 'Athens',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gr.svg',
	},
	GS: {
		countryCode: 'GS',
		countryName: 'South Georgia and the South Sandwich Islands',
		currencyCode: 'GBP',
		population: '30',
		capital: 'Grytviken',
		continentName: 'Antarctica',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gs.svg',
	},
	GT: {
		countryCode: 'GT',
		countryName: 'Guatemala',
		currencyCode: 'GTQ',
		population: '13550440',
		capital: 'Guatemala City',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gt.svg',
	},
	GU: {
		countryCode: 'GU',
		countryName: 'Guam',
		currencyCode: 'USD',
		population: '159358',
		capital: 'Hagåtña',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gu.svg',
	},
	GW: {
		countryCode: 'GW',
		countryName: 'Guinea-Bissau',
		currencyCode: 'XOF',
		population: '1565126',
		capital: 'Bissau',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gw.svg',
	},
	GY: {
		countryCode: 'GY',
		countryName: 'Guyana',
		currencyCode: 'GYD',
		population: '748486',
		capital: 'Georgetown',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/gy.svg',
	},
	HK: {
		countryCode: 'HK',
		countryName: 'Hong Kong',
		currencyCode: 'HKD',
		population: '6898686',
		capital: 'Hong Kong',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/hk.svg',
	},
	HM: {
		countryCode: 'HM',
		countryName: 'Heard Island and McDonald Islands',
		currencyCode: 'AUD',
		population: '0',
		capital: '',
		continentName: 'Antarctica',
	},
	HN: {
		countryCode: 'HN',
		countryName: 'Honduras',
		currencyCode: 'HNL',
		population: '7989415',
		capital: 'Tegucigalpa',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/hn.svg',
	},
	HR: {
		countryCode: 'HR',
		countryName: 'Croatia',
		currencyCode: 'HRK',
		population: '4284889',
		capital: 'Zagreb',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/hr.svg',
	},
	HT: {
		countryCode: 'HT',
		countryName: 'Haiti',
		currencyCode: 'HTG',
		population: '9648924',
		capital: 'Port-au-Prince',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ht.svg',
	},
	HU: {
		countryCode: 'HU',
		countryName: 'Hungary',
		currencyCode: 'HUF',
		population: '9982000',
		capital: 'Budapest',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/hu.svg',
	},
	ID: {
		countryCode: 'ID',
		countryName: 'Indonesia',
		currencyCode: 'IDR',
		population: '242968342',
		capital: 'Jakarta',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/id.svg',
	},
	IE: {
		countryCode: 'IE',
		countryName: 'Ireland',
		currencyCode: 'EUR',
		population: '4622917',
		capital: 'Dublin',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ie.svg',
	},
	IL: {
		countryCode: 'IL',
		countryName: 'Israel',
		currencyCode: 'ILS',
		population: '7353985',
		capital: '',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/il.svg',
	},
	IM: {
		countryCode: 'IM',
		countryName: 'Isle of Man',
		currencyCode: 'GBP',
		population: '75049',
		capital: 'Douglas',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/im.svg',
	},
	IN: {
		countryCode: 'IN',
		countryName: 'India',
		currencyCode: 'INR',
		population: '1173108018',
		capital: 'New Delhi',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/in.svg',
	},
	IO: {
		countryCode: 'IO',
		countryName: 'British Indian Ocean Territory',
		currencyCode: 'USD',
		population: '4000',
		capital: '',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/io.svg',
	},
	IQ: {
		countryCode: 'IQ',
		countryName: 'Iraq',
		currencyCode: 'IQD',
		population: '29671605',
		capital: 'Baghdad',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/iq.svg',
	},
	IR: {
		countryCode: 'IR',
		countryName: 'Iran',
		currencyCode: 'IRR',
		population: '76923300',
		capital: 'Tehran',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ir.svg',
	},
	IS: {
		countryCode: 'IS',
		countryName: 'Iceland',
		currencyCode: 'ISK',
		population: '308910',
		capital: 'Reykjavik',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/is.svg',
	},
	IT: {
		countryCode: 'IT',
		countryName: 'Italy',
		currencyCode: 'EUR',
		population: '60340328',
		capital: 'Rome',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/it.svg',
	},
	JE: {
		countryCode: 'JE',
		countryName: 'Jersey',
		currencyCode: 'GBP',
		population: '90812',
		capital: 'Saint Helier',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/je.svg',
	},
	JM: {
		countryCode: 'JM',
		countryName: 'Jamaica',
		currencyCode: 'JMD',
		population: '2847232',
		capital: 'Kingston',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/jm.svg',
	},
	JO: {
		countryCode: 'JO',
		countryName: 'Jordan',
		currencyCode: 'JOD',
		population: '6407085',
		capital: 'Amman',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/jo.svg',
	},
	JP: {
		countryCode: 'JP',
		countryName: 'Japan',
		currencyCode: 'JPY',
		population: '127288000',
		capital: 'Tokyo',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/jp.svg',
	},
	KE: {
		countryCode: 'KE',
		countryName: 'Kenya',
		currencyCode: 'KES',
		population: '40046566',
		capital: 'Nairobi',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ke.svg',
	},
	KG: {
		countryCode: 'KG',
		countryName: 'Kyrgyzstan',
		currencyCode: 'KGS',
		population: '5776500',
		capital: 'Bishkek',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kg.svg',
	},
	KH: {
		countryCode: 'KH',
		countryName: 'Cambodia',
		currencyCode: 'KHR',
		population: '14453680',
		capital: 'Phnom Penh',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kh.svg',
	},
	KI: {
		countryCode: 'KI',
		countryName: 'Kiribati',
		currencyCode: 'AUD',
		population: '92533',
		capital: 'Tarawa',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ki.svg',
	},
	KM: {
		countryCode: 'KM',
		countryName: 'Comoros',
		currencyCode: 'KMF',
		population: '773407',
		capital: 'Moroni',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/km.svg',
	},
	KN: {
		countryCode: 'KN',
		countryName: 'Saint Kitts and Nevis',
		currencyCode: 'XCD',
		population: '51134',
		capital: 'Basseterre',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kn.svg',
	},
	KP: {
		countryCode: 'KP',
		countryName: 'North Korea',
		currencyCode: 'KPW',
		population: '22912177',
		capital: 'Pyongyang',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kp.svg',
	},
	KR: {
		countryCode: 'KR',
		countryName: 'South Korea',
		currencyCode: 'KRW',
		population: '48422644',
		capital: 'Seoul',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kr.svg',
	},
	KW: {
		countryCode: 'KW',
		countryName: 'Kuwait',
		currencyCode: 'KWD',
		population: '2789132',
		capital: 'Kuwait City',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kw.svg',
	},
	KY: {
		countryCode: 'KY',
		countryName: 'Cayman Islands',
		currencyCode: 'KYD',
		population: '44270',
		capital: 'George Town',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ky.svg',
	},
	KZ: {
		countryCode: 'KZ',
		countryName: 'Kazakhstan',
		currencyCode: 'KZT',
		population: '15340000',
		capital: 'Astana',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/kz.svg',
	},
	LA: {
		countryCode: 'LA',
		countryName: 'Laos',
		currencyCode: 'LAK',
		population: '6368162',
		capital: 'Vientiane',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/la.svg',
	},
	LB: {
		countryCode: 'LB',
		countryName: 'Lebanon',
		currencyCode: 'LBP',
		population: '4125247',
		capital: 'Beirut',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lb.svg',
	},
	LC: {
		countryCode: 'LC',
		countryName: 'Saint Lucia',
		currencyCode: 'XCD',
		population: '160922',
		capital: 'Castries',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lc.svg',
	},
	LI: {
		countryCode: 'LI',
		countryName: 'Liechtenstein',
		currencyCode: 'CHF',
		population: '35000',
		capital: 'Vaduz',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/li.svg',
	},
	LK: {
		countryCode: 'LK',
		countryName: 'Sri Lanka',
		currencyCode: 'LKR',
		population: '21513990',
		capital: 'Colombo',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lk.svg',
	},
	LR: {
		countryCode: 'LR',
		countryName: 'Liberia',
		currencyCode: 'LRD',
		population: '3685076',
		capital: 'Monrovia',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lr.svg',
	},
	LS: {
		countryCode: 'LS',
		countryName: 'Lesotho',
		currencyCode: 'LSL',
		population: '1919552',
		capital: 'Maseru',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ls.svg',
	},
	LT: {
		countryCode: 'LT',
		countryName: 'Lithuania',
		currencyCode: 'EUR',
		population: '2944459',
		capital: 'Vilnius',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lt.svg',
	},
	LU: {
		countryCode: 'LU',
		countryName: 'Luxembourg',
		currencyCode: 'EUR',
		population: '497538',
		capital: 'Luxembourg',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lu.svg',
	},
	LV: {
		countryCode: 'LV',
		countryName: 'Latvia',
		currencyCode: 'EUR',
		population: '2217969',
		capital: 'Riga',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/lv.svg',
	},
	LY: {
		countryCode: 'LY',
		countryName: 'Libya',
		currencyCode: 'LYD',
		population: '6461454',
		capital: 'Tripoli',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ly.svg',
	},
	MA: {
		countryCode: 'MA',
		countryName: 'Morocco',
		currencyCode: 'MAD',
		population: '33848242',
		capital: 'Rabat',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ma.svg',
	},
	MC: {
		countryCode: 'MC',
		countryName: 'Monaco',
		currencyCode: 'EUR',
		population: '32965',
		capital: 'Monaco',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mc.svg',
	},
	MD: {
		countryCode: 'MD',
		countryName: 'Moldova',
		currencyCode: 'MDL',
		population: '4324000',
		capital: 'Chişinău',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/md.svg',
	},
	ME: {
		countryCode: 'ME',
		countryName: 'Montenegro',
		currencyCode: 'EUR',
		population: '666730',
		capital: 'Podgorica',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/me.svg',
	},
	MF: {
		countryCode: 'MF',
		countryName: 'Saint Martin',
		currencyCode: 'EUR',
		population: '35925',
		capital: 'Marigot',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mf.svg',
	},
	MG: {
		countryCode: 'MG',
		countryName: 'Madagascar',
		currencyCode: 'MGA',
		population: '21281844',
		capital: 'Antananarivo',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mg.svg',
	},
	MH: {
		countryCode: 'MH',
		countryName: 'Marshall Islands',
		currencyCode: 'USD',
		population: '65859',
		capital: 'Majuro',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mh.svg',
	},
	MK: {
		countryCode: 'MK',
		countryName: 'Macedonia',
		currencyCode: 'MKD',
		population: '2062294',
		capital: 'Skopje',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mk.svg',
	},
	ML: {
		countryCode: 'ML',
		countryName: 'Mali',
		currencyCode: 'XOF',
		population: '13796354',
		capital: 'Bamako',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ml.svg',
	},
	MM: {
		countryCode: 'MM',
		countryName: 'Myanmar [Burma]',
		currencyCode: 'MMK',
		population: '53414374',
		capital: 'Naypyitaw',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mm.svg',
	},
	MN: {
		countryCode: 'MN',
		countryName: 'Mongolia',
		currencyCode: 'MNT',
		population: '3086918',
		capital: 'Ulan Bator',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mn.svg',
	},
	MO: {
		countryCode: 'MO',
		countryName: 'Macao',
		currencyCode: 'MOP',
		population: '449198',
		capital: 'Macao',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mo.svg',
	},
	MP: {
		countryCode: 'MP',
		countryName: 'Northern Mariana Islands',
		currencyCode: 'USD',
		population: '53883',
		capital: 'Saipan',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mp.svg',
	},
	MQ: {
		countryCode: 'MQ',
		countryName: 'Martinique',
		currencyCode: 'EUR',
		population: '432900',
		capital: 'Fort-de-France',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mq.svg',
	},
	MR: {
		countryCode: 'MR',
		countryName: 'Mauritania',
		currencyCode: 'MRU',
		population: '3205060',
		capital: 'Nouakchott',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mr.svg',
	},
	MS: {
		countryCode: 'MS',
		countryName: 'Montserrat',
		currencyCode: 'XCD',
		population: '9341',
		capital: 'Plymouth',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ms.svg',
	},
	MT: {
		countryCode: 'MT',
		countryName: 'Malta',
		currencyCode: 'EUR',
		population: '403000',
		capital: 'Valletta',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mt.svg',
	},
	MU: {
		countryCode: 'MU',
		countryName: 'Mauritius',
		currencyCode: 'MUR',
		population: '1294104',
		capital: 'Port Louis',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mu.svg',
	},
	MV: {
		countryCode: 'MV',
		countryName: 'Maldives',
		currencyCode: 'MVR',
		population: '395650',
		capital: 'Malé',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mv.svg',
	},
	MW: {
		countryCode: 'MW',
		countryName: 'Malawi',
		currencyCode: 'MWK',
		population: '15447500',
		capital: 'Lilongwe',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mw.svg',
	},
	MX: {
		countryCode: 'MX',
		countryName: 'Mexico',
		currencyCode: 'MXN',
		population: '112468855',
		capital: 'Mexico City',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mx.svg',
	},
	MY: {
		countryCode: 'MY',
		countryName: 'Malaysia',
		currencyCode: 'MYR',
		population: '28274729',
		capital: 'Kuala Lumpur',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/my.svg',
	},
	MZ: {
		countryCode: 'MZ',
		countryName: 'Mozambique',
		currencyCode: 'MZN',
		population: '22061451',
		capital: 'Maputo',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/mz.svg',
	},
	NA: {
		countryCode: 'NA',
		countryName: 'Namibia',
		currencyCode: 'NAD',
		population: '2128471',
		capital: 'Windhoek',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/na.svg',
	},
	NC: {
		countryCode: 'NC',
		countryName: 'New Caledonia',
		currencyCode: 'XPF',
		population: '216494',
		capital: 'Noumea',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/nc.svg',
	},
	NE: {
		countryCode: 'NE',
		countryName: 'Niger',
		currencyCode: 'XOF',
		population: '15878271',
		capital: 'Niamey',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ne.svg',
	},
	NF: {
		countryCode: 'NF',
		countryName: 'Norfolk Island',
		currencyCode: 'AUD',
		population: '1828',
		capital: 'Kingston',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/nf.svg',
	},
	NG: {
		countryCode: 'NG',
		countryName: 'Nigeria',
		currencyCode: 'NGN',
		population: '154000000',
		capital: 'Abuja',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ng.svg',
	},
	NI: {
		countryCode: 'NI',
		countryName: 'Nicaragua',
		currencyCode: 'NIO',
		population: '5995928',
		capital: 'Managua',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ni.svg',
	},
	NL: {
		countryCode: 'NL',
		countryName: 'Netherlands',
		currencyCode: 'EUR',
		population: '16645000',
		capital: 'Amsterdam',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/nl.svg',
	},
	NO: {
		countryCode: 'NO',
		countryName: 'Norway',
		currencyCode: 'NOK',
		population: '5009150',
		capital: 'Oslo',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/no.svg',
	},
	NP: {
		countryCode: 'NP',
		countryName: 'Nepal',
		currencyCode: 'NPR',
		population: '28951852',
		capital: 'Kathmandu',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/np.svg',
	},
	NR: {
		countryCode: 'NR',
		countryName: 'Nauru',
		currencyCode: 'AUD',
		population: '10065',
		capital: 'Yaren',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/nr.svg',
	},
	NU: {
		countryCode: 'NU',
		countryName: 'Niue',
		currencyCode: 'NZD',
		population: '2166',
		capital: 'Alofi',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/nu.svg',
	},
	NZ: {
		countryCode: 'NZ',
		countryName: 'New Zealand',
		currencyCode: 'NZD',
		population: '4252277',
		capital: 'Wellington',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/nz.svg',
	},
	OM: {
		countryCode: 'OM',
		countryName: 'Oman',
		currencyCode: 'OMR',
		population: '2967717',
		capital: 'Muscat',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/om.svg',
	},
	PA: {
		countryCode: 'PA',
		countryName: 'Panama',
		currencyCode: 'PAB',
		population: '3410676',
		capital: 'Panama City',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pa.svg',
	},
	PE: {
		countryCode: 'PE',
		countryName: 'Peru',
		currencyCode: 'PEN',
		population: '29907003',
		capital: 'Lima',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pe.svg',
	},
	PF: {
		countryCode: 'PF',
		countryName: 'French Polynesia',
		currencyCode: 'XPF',
		population: '270485',
		capital: 'Papeete',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pf.svg',
	},
	PG: {
		countryCode: 'PG',
		countryName: 'Papua New Guinea',
		currencyCode: 'PGK',
		population: '6064515',
		capital: 'Port Moresby',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pg.svg',
	},
	PH: {
		countryCode: 'PH',
		countryName: 'Philippines',
		currencyCode: 'PHP',
		population: '99900177',
		capital: 'Manila',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ph.svg',
	},
	PK: {
		countryCode: 'PK',
		countryName: 'Pakistan',
		currencyCode: 'PKR',
		population: '184404791',
		capital: 'Islamabad',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pk.svg',
	},
	PL: {
		countryCode: 'PL',
		countryName: 'Poland',
		currencyCode: 'PLN',
		population: '38500000',
		capital: 'Warsaw',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pl.svg',
	},
	PM: {
		countryCode: 'PM',
		countryName: 'Saint Pierre and Miquelon',
		currencyCode: 'EUR',
		population: '7012',
		capital: 'Saint-Pierre',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pm.svg',
	},
	PN: {
		countryCode: 'PN',
		countryName: 'Pitcairn Islands',
		currencyCode: 'NZD',
		population: '46',
		capital: 'Adamstown',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pn.svg',
	},
	PR: {
		countryCode: 'PR',
		countryName: 'Puerto Rico',
		currencyCode: 'USD',
		population: '3916632',
		capital: 'San Juan',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pr.svg',
	},
	PS: {
		countryCode: 'PS',
		countryName: 'Palestine',
		currencyCode: 'ILS',
		population: '3800000',
		capital: '',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ps.svg',
	},
	PT: {
		countryCode: 'PT',
		countryName: 'Portugal',
		currencyCode: 'EUR',
		population: '10676000',
		capital: 'Lisbon',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pt.svg',
	},
	PW: {
		countryCode: 'PW',
		countryName: 'Palau',
		currencyCode: 'USD',
		population: '19907',
		capital: 'Melekeok',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/pw.svg',
	},
	PY: {
		countryCode: 'PY',
		countryName: 'Paraguay',
		currencyCode: 'PYG',
		population: '6375830',
		capital: 'Asunción',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/py.svg',
	},
	QA: {
		countryCode: 'QA',
		countryName: 'Qatar',
		currencyCode: 'QAR',
		population: '840926',
		capital: 'Doha',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/qa.svg',
	},
	RE: {
		countryCode: 'RE',
		countryName: 'Réunion',
		currencyCode: 'EUR',
		population: '776948',
		capital: 'Saint-Denis',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/re.svg',
	},
	RO: {
		countryCode: 'RO',
		countryName: 'Romania',
		currencyCode: 'RON',
		population: '21959278',
		capital: 'Bucharest',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ro.svg',
	},
	RS: {
		countryCode: 'RS',
		countryName: 'Serbia',
		currencyCode: 'RSD',
		population: '7344847',
		capital: 'Belgrade',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/rs.svg',
	},
	RU: {
		countryCode: 'RU',
		countryName: 'Russia',
		currencyCode: 'RUB',
		population: '140702000',
		capital: 'Moscow',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ru.svg',
	},
	RW: {
		countryCode: 'RW',
		countryName: 'Rwanda',
		currencyCode: 'RWF',
		population: '11055976',
		capital: 'Kigali',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/rw.svg',
	},
	SA: {
		countryCode: 'SA',
		countryName: 'Saudi Arabia',
		currencyCode: 'SAR',
		population: '25731776',
		capital: 'Riyadh',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sa.svg',
	},
	SB: {
		countryCode: 'SB',
		countryName: 'Solomon Islands',
		currencyCode: 'SBD',
		population: '559198',
		capital: 'Honiara',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sb.svg',
	},
	SC: {
		countryCode: 'SC',
		countryName: 'Seychelles',
		currencyCode: 'SCR',
		population: '88340',
		capital: 'Victoria',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sc.svg',
	},
	SD: {
		countryCode: 'SD',
		countryName: 'Sudan',
		currencyCode: 'SDG',
		population: '35000000',
		capital: 'Khartoum',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sd.svg',
	},
	SE: {
		countryCode: 'SE',
		countryName: 'Sweden',
		currencyCode: 'SEK',
		population: '9828655',
		capital: 'Stockholm',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/se.svg',
	},
	SG: {
		countryCode: 'SG',
		countryName: 'Singapore',
		currencyCode: 'SGD',
		population: '4701069',
		capital: 'Singapore',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sg.svg',
	},
	SH: {
		countryCode: 'SH',
		countryName: 'Saint Helena',
		currencyCode: 'SHP',
		population: '7460',
		capital: 'Jamestown',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sh.svg',
	},
	SI: {
		countryCode: 'SI',
		countryName: 'Slovenia',
		currencyCode: 'EUR',
		population: '2007000',
		capital: 'Ljubljana',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/si.svg',
	},
	SJ: {
		countryCode: 'SJ',
		countryName: 'Svalbard and Jan Mayen',
		currencyCode: 'NOK',
		population: '2550',
		capital: 'Longyearbyen',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sj.svg',
	},
	SK: {
		countryCode: 'SK',
		countryName: 'Slovakia',
		currencyCode: 'EUR',
		population: '5455000',
		capital: 'Bratislava',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sk.svg',
	},
	SL: {
		countryCode: 'SL',
		countryName: 'Sierra Leone',
		currencyCode: 'SLL',
		population: '5245695',
		capital: 'Freetown',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sl.svg',
	},
	SM: {
		countryCode: 'SM',
		countryName: 'San Marino',
		currencyCode: 'EUR',
		population: '31477',
		capital: 'San Marino',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sm.svg',
	},
	SN: {
		countryCode: 'SN',
		countryName: 'Senegal',
		currencyCode: 'XOF',
		population: '12323252',
		capital: 'Dakar',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sn.svg',
	},
	SO: {
		countryCode: 'SO',
		countryName: 'Somalia',
		currencyCode: 'SOS',
		population: '10112453',
		capital: 'Mogadishu',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/so.svg',
	},
	SR: {
		countryCode: 'SR',
		countryName: 'Suriname',
		currencyCode: 'SRD',
		population: '492829',
		capital: 'Paramaribo',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sr.svg',
	},
	SS: {
		countryCode: 'SS',
		countryName: 'South Sudan',
		currencyCode: 'SSP',
		population: '8260490',
		capital: 'Juba',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ss.svg',
	},
	ST: {
		countryCode: 'ST',
		countryName: 'São Tomé and Príncipe',
		currencyCode: 'STN',
		population: '175808',
		capital: 'São Tomé',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/st.svg',
	},
	SV: {
		countryCode: 'SV',
		countryName: 'El Salvador',
		currencyCode: 'USD',
		population: '6052064',
		capital: 'San Salvador',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sv.svg',
	},
	SX: {
		countryCode: 'SX',
		countryName: 'Sint Maarten',
		currencyCode: 'ANG',
		population: '37429',
		capital: 'Philipsburg',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sx.svg',
	},
	SY: {
		countryCode: 'SY',
		countryName: 'Syria',
		currencyCode: 'SYP',
		population: '22198110',
		capital: 'Damascus',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sy.svg',
	},
	SZ: {
		countryCode: 'SZ',
		countryName: 'Swaziland',
		currencyCode: 'SZL',
		population: '1354051',
		capital: 'Mbabane',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/sz.svg',
	},
	TC: {
		countryCode: 'TC',
		countryName: 'Turks and Caicos Islands',
		currencyCode: 'USD',
		population: '20556',
		capital: 'Cockburn Town',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tc.svg',
	},
	TD: {
		countryCode: 'TD',
		countryName: 'Chad',
		currencyCode: 'XAF',
		population: '10543464',
		capital: "N'Djamena",
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/td.svg',
	},
	TF: {
		countryCode: 'TF',
		countryName: 'French Southern Territories',
		currencyCode: 'EUR',
		population: '140',
		capital: 'Port-aux-Français',
		continentName: 'Antarctica',
	},
	TG: {
		countryCode: 'TG',
		countryName: 'Togo',
		currencyCode: 'XOF',
		population: '6587239',
		capital: 'Lomé',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tg.svg',
	},
	TH: {
		countryCode: 'TH',
		countryName: 'Thailand',
		currencyCode: 'THB',
		population: '67089500',
		capital: 'Bangkok',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/th.svg',
	},
	TJ: {
		countryCode: 'TJ',
		countryName: 'Tajikistan',
		currencyCode: 'TJS',
		population: '7487489',
		capital: 'Dushanbe',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tj.svg',
	},
	TK: {
		countryCode: 'TK',
		countryName: 'Tokelau',
		currencyCode: 'NZD',
		population: '1466',
		capital: '',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tk.svg',
	},
	TL: {
		countryCode: 'TL',
		countryName: 'East Timor',
		currencyCode: 'USD',
		population: '1154625',
		capital: 'Dili',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tl.svg',
	},
	TM: {
		countryCode: 'TM',
		countryName: 'Turkmenistan',
		currencyCode: 'TMT',
		population: '4940916',
		capital: 'Ashgabat',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tm.svg',
	},
	TN: {
		countryCode: 'TN',
		countryName: 'Tunisia',
		currencyCode: 'TND',
		population: '10589025',
		capital: 'Tunis',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tn.svg',
	},
	TO: {
		countryCode: 'TO',
		countryName: 'Tonga',
		currencyCode: 'TOP',
		population: '122580',
		capital: "Nuku'alofa",
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/to.svg',
	},
	TR: {
		countryCode: 'TR',
		countryName: 'Turkey',
		currencyCode: 'TRY',
		population: '77804122',
		capital: 'Ankara',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tr.svg',
	},
	TT: {
		countryCode: 'TT',
		countryName: 'Trinidad and Tobago',
		currencyCode: 'TTD',
		population: '1228691',
		capital: 'Port of Spain',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tt.svg',
	},
	TV: {
		countryCode: 'TV',
		countryName: 'Tuvalu',
		currencyCode: 'AUD',
		population: '10472',
		capital: 'Funafuti',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tv.svg',
	},
	TW: {
		countryCode: 'TW',
		countryName: 'Taiwan',
		currencyCode: 'TWD',
		population: '22894384',
		capital: 'Taipei',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tw.svg',
	},
	TZ: {
		countryCode: 'TZ',
		countryName: 'Tanzania',
		currencyCode: 'TZS',
		population: '41892895',
		capital: 'Dodoma',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/tz.svg',
	},
	UA: {
		countryCode: 'UA',
		countryName: 'Ukraine',
		currencyCode: 'UAH',
		population: '45415596',
		capital: 'Kiev',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ua.svg',
	},
	UG: {
		countryCode: 'UG',
		countryName: 'Uganda',
		currencyCode: 'UGX',
		population: '33398682',
		capital: 'Kampala',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ug.svg',
	},
	UM: {
		countryCode: 'UM',
		countryName: 'U.S. Minor Outlying Islands',
		currencyCode: 'USD',
		population: '0',
		capital: '',
		continentName: 'Oceania',
	},
	US: {
		countryCode: 'US',
		countryName: 'United States',
		currencyCode: 'USD',
		population: '310232863',
		capital: 'Washington',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/us.svg',
	},
	UY: {
		countryCode: 'UY',
		countryName: 'Uruguay',
		currencyCode: 'UYU',
		population: '3477000',
		capital: 'Montevideo',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/uy.svg',
	},
	UZ: {
		countryCode: 'UZ',
		countryName: 'Uzbekistan',
		currencyCode: 'UZS',
		population: '27865738',
		capital: 'Tashkent',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/uz.svg',
	},
	VA: {
		countryCode: 'VA',
		countryName: 'Vatican City',
		currencyCode: 'EUR',
		population: '921',
		capital: 'Vatican City',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/va.svg',
	},
	VC: {
		countryCode: 'VC',
		countryName: 'Saint Vincent and the Grenadines',
		currencyCode: 'XCD',
		population: '104217',
		capital: 'Kingstown',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/vc.svg',
	},
	VE: {
		countryCode: 'VE',
		countryName: 'Venezuela',
		currencyCode: 'VES',
		population: '27223228',
		capital: 'Caracas',
		continentName: 'South America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ve.svg',
	},
	VG: {
		countryCode: 'VG',
		countryName: 'British Virgin Islands',
		currencyCode: 'USD',
		population: '21730',
		capital: 'Road Town',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/vg.svg',
	},
	VI: {
		countryCode: 'VI',
		countryName: 'U.S. Virgin Islands',
		currencyCode: 'USD',
		population: '108708',
		capital: 'Charlotte Amalie',
		continentName: 'North America',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/vi.svg',
	},
	VN: {
		countryCode: 'VN',
		countryName: 'Vietnam',
		currencyCode: 'VND',
		population: '89571130',
		capital: 'Hanoi',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/vn.svg',
	},
	VU: {
		countryCode: 'VU',
		countryName: 'Vanuatu',
		currencyCode: 'VUV',
		population: '221552',
		capital: 'Port Vila',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/vu.svg',
	},
	WF: {
		countryCode: 'WF',
		countryName: 'Wallis and Futuna',
		currencyCode: 'XPF',
		population: '16025',
		capital: 'Mata-Utu',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/wf.svg',
	},
	WS: {
		countryCode: 'WS',
		countryName: 'Samoa',
		currencyCode: 'WST',
		population: '192001',
		capital: 'Apia',
		continentName: 'Oceania',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ws.svg',
	},
	XK: {
		countryCode: 'XK',
		countryName: 'Kosovo',
		currencyCode: 'EUR',
		population: '1800000',
		capital: 'Pristina',
		continentName: 'Europe',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/xk.svg',
	},
	YE: {
		countryCode: 'YE',
		countryName: 'Yemen',
		currencyCode: 'YER',
		population: '23495361',
		capital: 'Sanaa',
		continentName: 'Asia',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/ye.svg',
	},
	YT: {
		countryCode: 'YT',
		countryName: 'Mayotte',
		currencyCode: 'EUR',
		population: '159042',
		capital: 'Mamoudzou',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/yt.svg',
	},
	ZA: {
		countryCode: 'ZA',
		countryName: 'South Africa',
		currencyCode: 'ZAR',
		population: '49000000',
		capital: 'Pretoria',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/za.svg',
	},
	ZM: {
		countryCode: 'ZM',
		countryName: 'Zambia',
		currencyCode: 'ZMW',
		population: '13460305',
		capital: 'Lusaka',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/zm.svg',
	},
	ZW: {
		countryCode: 'ZW',
		countryName: 'Zimbabwe',
		currencyCode: 'ZWL',
		population: '13061000',
		capital: 'Harare',
		continentName: 'Africa',
		flag: 'https://cdn.kcak11.com/CountryFlags/countries/zw.svg',
	},
}
